name: CustomFishing
version: '${version}'
main: net.momirealms.customfishing.CustomFishing
api-version: 1.17
authors: [ XiaoMoMi ]
softdepend:
  - MythicMobs
  - PlaceholderAPI
  - WorldGuard
  - mcMMO
  - AureliumSkills
  - MMOCore
  - EcoSkills
  - EcoEnchants
  - RealisticSeasons
  - CustomCrops
  - ItemsAdder
  - Oraxen
  - MMOItems
commands:
  customfishing:
    usage: /customfishing
    description: main command
    permission: customfishing.admin
    aliases:
      - cfishing