name: CustomFishing
version: '${version}'
main: net.momirealms.customfishing.CustomFishing
api-version: 1.17
authors: [ XiaoMoMi ]
folia-supported: true
depend:
  - ProtocolLib
softdepend:
  - ItemsAdder
  - MythicMobs
  - Oraxen
  - PlaceholderAPI
  - EcoEnchants
  - mcMMO
  - AureliumSkills
  - CustomCrops
  - MMOCore
  - EcoSkills
  - RealisticSeasons
  - Jobs
  - MMOItems
  - eco
  - Vault
  - BattlePass
  - ClueScrolls
  - BetonQuest
  - AdvancedEnchantments
  - EcoJobs

commands:
  customfishing:
    usage: /customfishing
    description: main command
    permission: customfishing.admin
    aliases:
      - cfishing
  fishingbag:
    usage: /fishingbag open
    description: fishing bag command
  sellfish:
    usage: /sellfish
    description: sell fish command
    permission: customfishing.sellfish

permissions:
  customfishing.*:
    description: Gives access to all customfishing commands
    children:
      customfishing.admin: true
      customfishing.sellfish: true
      customfishing.fishingbag: true

  customfishing.admin:
    default: op
  customfishing.sellfish:
    default: true
  fishingbag.rows.1:
    default: true
  fishingbag.rows.2:
    default: false
  fishingbag.rows.3:
    default: false
  fishingbag.rows.4:
    default: false
  fishingbag.rows.5:
    default: false
  fishingbag.rows.6:
    default: false
  fishingbag.open:
    default: true