# Note: These are the default configurations of the plugin
# and do not necessarily mean that players can have a good
# gaming experience. We hope that you will create
# customized configurations based on your own ideas,
# allowing players to experience the uniqueness of your server.

apple_crate:
  show-in-fishfinder: false
  disable-stat: true
  nick: Apple Crate
  block: barrel
  velocity:
    horizontal: 1.07
    vertical: 1.5
  properties:
    directional-6: true
    storage:
      apple_1:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_2:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_3:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_4:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_5:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_6:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_7:
        item: APPLE
        amount: 1~2
        chance: 0.8
      apple_8:
        item: APPLE
        amount: 1~2
        chance: 0.8
carrot_crate:
  show-in-fishfinder: false
  disable-stat: true
  nick: Carrot Crate
  block: barrel
  velocity:
    horizontal: 1.07
    vertical: 1.5
  properties:
    directional-6: true
    storage:
      carrot_1:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_2:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_3:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_4:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_5:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_6:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_7:
        item: CARROT
        amount: 1~2
        chance: 0.8
      carrot_8:
        item: CARROT
        amount: 1~2
        chance: 0.8