# Note: These are the default configurations of the plugin
# and do not necessarily mean that players can have a good
# gaming experience. We hope that you will create
# customized configurations based on your own ideas,
# allowing players to experience the uniqueness of your server.

skeleton:
  show-in-fishfinder: false
  disable-stat: true
  disable-game: true
  entity: skeleton
  nick: <white>Skeleton</white>
  velocity:
    horizontal: 1.1
    vertical: 1.3

wither_skeleton:
  show-in-fishfinder: false
  disable-stat: true
  disable-game: true
  entity: wither_skeleton
  nick: <black>Wither Skeleton</black>
  velocity:
    horizontal: 1.1
    vertical: 1.2

magma_cube:
  show-in-fishfinder: false
  disable-stat: true
  disable-game: true
  entity: magma_cube
  nick: <red>Magma Cube</black>
  velocity:
    horizontal: 1.1
    vertical: 1.3

skeletalknight:
  show-in-fishfinder: false
  disable-stat: true
  disable-game: true
  entity: MythicMobs:SkeletalKnight
  nick: Skeletal Knight
  velocity:
    horizontal: 1.1
    vertical: 1.2
  properties:
    level: 0.0