# Note: These are the default configurations of the plugin
# and do not necessarily mean that players can have a good
# gaming experience. We hope that you will create
# customized configurations based on your own ideas,
# allowing players to experience the uniqueness of your server.

double_loot_totem:
  radius: 8
  duration: 300
  pattern:
    core: 3,1,2 # layer:3 line:1 index:2 -> CRYING_OBSIDIAN
    layer:
      4:
        - '*_STAIRS{face=east;half=top} OBSERVER{face=south} *_STAIRS{face=west;half=top}'
      3:
        - 'AIR                            CRYING_OBSIDIAN                             AIR'
      2:
        - 'AIR                     *_LOG{axis=y}||*_PILLAR{axis=y}                    AIR'
      1:
        - 'AIR||GRASS||SNOW                   ANVIL                      AIR||GRASS||SNOW'
  effects:
    effect_1:
      type: multiple-loot
      value: 1.0
  requirements:
    requirement_1:
      type: item-in-hand
      value:
        item: NAUTILUS_SHELL
        amount: 1
      not-met-actions:
        action_1:
          type: message
          value:
            - '<#BA55D3>[Totem]</#BA55D3> <#F5FFFA>Hold a nautilus shell in main hand to activate the totem.'
  events:
    timer:
      actionbar_action:
        type: actionbar-nearby
        value:
          actionbar: '<#BA55D3>[Double Loot Totem]</#BA55D3> Time Left: {time_left} seconds'
          range: 16
      hologram_action_1:
        type: hologram
        value:
          duration: 20
          text: '<#BA55D3>[Double Loot Totem]</#BA55D3>'
          position: other
          range: 16
          use-text-display: true
          rgba: 147,112,219,50
          y: 3.3
          x: 0
          z: 0
      hologram_action_2:
        type: hologram
        value:
          duration: 20
          text: 'Time Left: {time_left} seconds'
          position: other
          range: 16
          use-text-display: true
          y: 2.8
          x: 0
          z: 0
    activate:
      remove_item_action:
        type: item-amount
        value:
          amount: -1
      broadcast_action:
        type: message-nearby
        value:
          message:
            - '<#BA55D3>[Totem]</#BA55D3> <#F5FFFA>{player}</#F5FFFA> <#F5F5F5>activated a totem nearby!</#F5F5F5>'
          range: 32
  particles:
    particle_01:
      type: REDSTONE
      options:
        color: 186,85,211
        scale: 0.8
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 30
        range:
          - 0~359
      task:
        period: 5
        delay: 0
    particle_02:
      type: REDSTONE
      options:
        color: 148,0,211
        scale: 1.1
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 30
        range:
          - 6~365
      task:
        period: 5
        delay: 1
    particle_03:
      type: REDSTONE
      options:
        color: 147,112,219
        scale: 1.5
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 30
        range:
          - 12~371
      task:
        period: 5
        delay: 2
    particle_04:
      type: REDSTONE
      options:
        color: 123,104,238
        scale: 2
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 30
        range:
          - 18~377
      task:
        period: 5
        delay: 3
    particle_05:
      type: REDSTONE
      options:
        color: 30,144,255
        scale: 2.5
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 30
        range:
          - 24~383
      task:
        period: 5
        delay: 4
    particle_06:
      type: DRIPPING_OBSIDIAN_TEAR
      options:
        color: 30,144,255
        scale: 3
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 90
        range:
          - 0~359
      task:
        period: 40
        delay: 0
    particle_07:
      type: DRIPPING_OBSIDIAN_TEAR
      options:
        color: 30,144,255
        scale: 3
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 90
        range:
          - 22.5~382
      task:
        period: 40
        delay: 10
    particle_08:
      type: DRIPPING_OBSIDIAN_TEAR
      options:
        color: 30,144,255
        scale: 3
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 90
        range:
          - 45~404
      task:
        period: 40
        delay: 20
    particle_09:
      type: DRIPPING_OBSIDIAN_TEAR
      options:
        color: 30,144,255
        scale: 3
      polar-coordinates-formula:
        horizontal: '{radius}'
        vertical: '3'
      theta:
        draw-interval: 90
        range:
          - 67.5~427
      task:
        period: 40
        delay: 20
golden_star_totem:
  radius: 10
  duration: 120
  pattern:
    core: 4,2,2 # layer:4 line:2 index:2 -> DAYLIGHT_DETECTOR
    layer:
      4:
        - 'AIR        AIR        AIR'
        - 'AIR DAYLIGHT_DETECTOR AIR'
        - 'AIR        AIR        AIR'
      3:
        - 'AIR      AIR      AIR'
        - 'AIR LIGHTNING_ROD AIR'
        - 'AIR      AIR      AIR'
      2:
        - 'AIR    AIR     AIR'
        - 'AIR GOLD_BLOCK AIR'
        - 'AIR    AIR     AIR'
      1:
        - 'AIR        GOLD_BLOCK        AIR'
        - 'GOLD_BLOCK GOLD_BLOCK GOLD_BLOCK'
        - 'AIR        GOLD_BLOCK        AIR'
  particles:
    particle_01:
      type: REDSTONE
      options:
        color: 255,215,0
        scale: 3
      polar-coordinates-formula:
        horizontal: '{radius} + sin({theta} * 5) * 2.5'
        vertical: '-2.5'
      theta:
        draw-interval: 5
        range:
          - 0~360
      task:
        period: 5
        delay: 0
  effects:
    effect_1:
      type: group-mod
      value:
        - golden_star:+15
  requirements:
    requirement_1:
      type: item-in-hand
      value:
        item: GOLD_INGOT
        amount: 1
      not-met-actions:
        action_1:
          type: message
          value:
            - '<#BA55D3>[TotemActivation]</#BA55D3> <#F5FFFA>Hold a gold ingot in main hand to activate the totem.'
  events:
    timer:
      actionbar_action:
        type: actionbar-nearby
        value:
          actionbar: '<#FFFF00>[Golden Star Totem]</#FFFF00> Time Left: {time_left} seconds'
          range: 16
      hologram_action_1:
        type: hologram
        value:
          duration: 20
          text: '<#FFFF00>[Golden Star Totem]</#FFFF00>'
          position: other
          range: 16
          use-text-display: true
          rgba: 255,215,0,50
          y: 1
          x: 0
          z: 0
      hologram_action_2:
        type: hologram
        value:
          duration: 20
          text: 'Time Left: {time_left} seconds'
          position: other
          use-text-display: true
          range: 16
          y: 0.5
          x: 0
          z: 0
    activate:
      remove_item_action:
        type: item-amount
        value:
          amount: -1
      broadcast_action:
        type: message-nearby
        value:
          message:
            - '<#FFFF00>[TotemActivation]</#FFFF00> <#F5FFFA>{player}</#F5FFFA> <#F5F5F5>activated a totem nearby!</#F5F5F5>'
          range: 32