name: Java CI with Gradle
on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 17
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
      - name: 'Set up JDK ${{ matrix.java }}'
        uses: actions/setup-java@v4.2.1
        with:
          distribution: adopt
          java-version: '${{ matrix.java }}'
      - name: Cache Gradle
        uses: actions/cache@v4.0.2
        with:
          path: ~/.gradle/caches
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: '${{ runner.os }}-gradle-'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build the Jar
        run: './gradlew build'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: 'CustomFishing'
          path: target/CustomFishing-*.jar
